version: "3.9"

services:
    postgres:
      image: postgres:15
      container_name: walletwave-postgres
      restart: unless-stopped
      environment: 
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: WalletWave
      ports:
        - "5433:5432"
      volumes:
         - postgres_data:/var/lib/postgresql/data

    redis:
       image: redis:alpine
       container_name: walletwave-redis
       ports: 
         - "6379:6379"
       restart: unless-stopped
       command: redis-server --appendonly yes
       healthcheck:
          test: ["CMD","redis-cli","ping"]
          interval: 10s
          timeout: 5s
          retries: 5


    backend:
      build:
        context: .
        target: builder
      container_name: walletwave-backend
      restart: unless-stopped
      command: ["sh","-c","npm run db:deploy && npm run dev:server"]
      ports:
        - "8000:8000"
      volumes:
         - ./:/app:delegated
         - node_modules:/app/node_modules
      env_file:
        - .env
      depends_on:
        - postgres
        - redis

    worker:
      build:
        context: .
        target: builder
      depends_on:
         - postgres
         - redis
      volumes:
         - ./:/app:delegated
         - node_modules:/app/node_modules
      env_file:
        - .env
      command: ["sh","-c","npm run db:deploy && npm run dev:worker"]

volumes:
  node_modules:
  postgres_data:


    

    
      